# Generated by Django 5.2.15 on 2026-06-24 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_id",
                    models.BigIntegerField(
                        help_text="Organt 두뇌의 봇 id", unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="직군(백엔드/QA/…)", max_length=60
                    ),
                ),
                ("is_leader", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["role", "bot_id"],
            },
        ),
        migrations.CreateModel(
            name="RoleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=60, unique=True)),
                (
                    "criteria",
                    models.TextField(
                        blank=True, help_text="증류된 직무기준(품질 루브릭)"
                    ),
                ),
                (
                    "experience_count",
                    models.IntegerField(
                        default=0, help_text="아직 증류 안 된 원석 경험 수"
                    ),
                ),
                (
                    "distill_count",
                    models.IntegerField(
                        default=0, help_text="누적 증류 횟수(성장 지표)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-distill_count", "role"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    models.CharField(help_text="P-032 등", max_length=20, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_projects",
                        to="sns.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["pid"],
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="sns.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(default="익명", max_length=60)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="sns.thread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.BigIntegerField(help_text="ingest 단조 시퀀스", unique=True),
                ),
                ("ts", models.FloatField(help_text="epoch seconds")),
                ("source", models.CharField(help_text="flow|audit", max_length=10)),
                (
                    "kind",
                    models.CharField(
                        db_index=True,
                        help_text="delegation/consultation/work/verification/...",
                        max_length=30,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="sns.agent",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_events",
                        to="sns.agent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="sns.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-seq"],
                "indexes": [
                    models.Index(fields=["-seq"], name="sns_event_seq_db83b9_idx"),
                    models.Index(fields=["kind"], name="sns_event_kind_5d2c1f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CollabTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=40)),
                ("purpose", models.TextField(blank=True)),
                ("goal", models.TextField(blank=True)),
                ("cross_checks", models.IntegerField(default=0)),
                ("deploy_count", models.IntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_tasks",
                        to="sns.agent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="sns.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "task_id")},
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_key",
                    models.CharField(help_text="익명/세션 식별 키", max_length=80),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="sns.thread",
                    ),
                ),
            ],
            options={
                "unique_together": {("thread", "user_key")},
            },
        ),
    ]
