# Generated by Django 5.2.15 on 2026-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideMessage",
            fields=[
                ("msg_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("channel_id", models.BigIntegerField(db_index=True)),
                ("thread_id", models.BigIntegerField(db_index=True)),
                ("sender_id", models.BigIntegerField(default=0)),
                (
                    "msg_type",
                    models.CharField(
                        choices=[
                            ("plain", "평문"),
                            ("request", "요청"),
                            ("response", "응답"),
                            ("status", "상태블록"),
                        ],
                        default="plain",
                        max_length=10,
                    ),
                ),
                ("to_id", models.BigIntegerField(blank=True, null=True)),
                ("kind", models.CharField(blank=True, max_length=1)),
                ("reply_to", models.BigIntegerField(blank=True, null=True)),
                ("body", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("edited", models.BooleanField(default=False)),
                ("ts", models.FloatField()),
            ],
            options={
                "ordering": ["msg_id"],
                "indexes": [
                    models.Index(
                        fields=["thread_id", "msg_id"],
                        name="sns_guideme_thread__ec06ef_idx",
                    ),
                    models.Index(
                        fields=["channel_id", "msg_id"],
                        name="sns_guideme_channel_786072_idx",
                    ),
                ],
            },
        ),
    ]
