# Generated by Django 5.2.15 on 2026-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0002_guidemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="avatar",
            field=models.CharField(
                blank=True, help_text="[커스텀] 이모지 아바타", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="created_via",
            field=models.CharField(
                default="discord",
                help_text="discord(두뇌 채용) | sns(스튜디오 채용)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="persona",
            field=models.TextField(
                blank=True, help_text="[커스텀] 봇 인격(시스템 프롬프트)"
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="bot_id",
            field=models.BigIntegerField(
                help_text="봇 id(디스코드 or SNS 생성)", unique=True
            ),
        ),
    ]
