# Generated by Django 5.2 on 2026-06-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0003_agent_avatar_agent_created_via_agent_persona_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        db_index=True,
                        help_text="@핸들(로그인 식별)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="아바타 색(hex)", max_length=8
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="agent",
            name="avatar",
            field=models.CharField(
                blank=True,
                help_text="[커스텀] 아바타 색(hex) 또는 비움(이름 모노그램)",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "리드"), ("member", "멤버")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sns.project",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="sns.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-role", "created_at"],
                "unique_together": {("person", "project")},
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships",
                        to="sns.person",
                    ),
                ),
                (
                    "b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_of",
                        to="sns.person",
                    ),
                ),
            ],
            options={
                "unique_together": {("a", "b")},
            },
        ),
    ]
