# Generated by Django 5.2.15 on 2026-06-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0004_person_alter_agent_avatar_membership_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_guest",
            field=models.BooleanField(default=False, help_text="둘러보기 체험 계정"),
        ),
        migrations.AddField(
            model_name="person",
            name="password",
            field=models.CharField(
                blank=True, help_text="Django 해시(set_password)", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="인증 토큰(Authorization)",
                max_length=48,
            ),
        ),
    ]
