# Generated by Django 5.2.15 on 2026-06-24 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0005_person_is_guest_person_password_person_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="소유자(사용자가 채용한 '나만의 직원'). null=공개 쇼케이스 직원",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_agents",
                to="sns.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="채널 소유자(만든 사람). null=공개 쇼케이스 채널",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projects",
                to="sns.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("public", "공개"), ("private", "비공개")],
                db_index=True,
                default="public",
                max_length=10,
            ),
        ),
    ]
