# Generated by Django 5.2.15 on 2026-06-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0006_agent_owner_project_owner_project_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="visibility",
            field=models.CharField(
                choices=[("public", "공개"), ("private", "비공개")],
                db_index=True,
                default="public",
                max_length=10,
            ),
        ),
    ]
