# Generated by Django 5.2.15 on 2026-06-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0007_agent_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[("pending", "요청됨"), ("accepted", "수락됨")],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[("invited", "초대됨"), ("active", "참여중")],
                db_index=True,
                default="active",
                max_length=10,
            ),
        ),
    ]
