# Generated by Django 5.2.15 on 2026-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0008_friendship_status_membership_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_beat", models.FloatField(default=0.0)),
                ("note", models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
