# Generated by Django 5.2.15 on 2026-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0009_engineheartbeat"),
    ]

    operations = [
        migrations.CreateModel(
            name="StopSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField(db_index=True, unique=True)),
                ("requested_at", models.FloatField(default=0.0)),
                ("requested_by", models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
