# Generated by Django 5.2.15 on 2026-06-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0010_stopsignal"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="model",
            field=models.CharField(
                blank=True,
                help_text="[per-agent 모델] 이 직원이 쓸 LLM(opus/sonnet/haiku). 비우면 러너 전역 기본",
                max_length=20,
            ),
        ),
    ]
