# Generated by Django 5.2.15 on 2026-06-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0011_agent_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterjectSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.BigIntegerField(db_index=True)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("text", models.TextField()),
                ("requested_at", models.FloatField(default=0.0)),
                ("requested_by", models.CharField(blank=True, max_length=30)),
                ("requester_name", models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
