# Generated by Django 5.2.15 on 2026-06-29 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sns", "0012_interjectsignal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="키 이름(RENDER_KEY 등)", max_length=64),
                ),
                (
                    "value_enc",
                    models.TextField(help_text="Fernet 암호문 — 평문 저장 금지"),
                ),
                (
                    "hint",
                    models.CharField(
                        blank=True,
                        help_text="확인용 힌트(••••마지막4자) — 값 아님",
                        max_length=12,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="sns.person",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("person", "name")},
            },
        ),
    ]
